// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADbGCXo2IN-DGmMRAfFHgdzdKYtaC2lMI',
    appId: '1:63571296037:web:83fd41c4a3b1d2a94764cc',
    messagingSenderId: '63571296037',
    projectId: 'flutterproject-72d57',
    authDomain: 'flutterproject-72d57.firebaseapp.com',
    storageBucket: 'flutterproject-72d57.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrqRWJL5gehmw6es-iMblEqJTEHor-H-U',
    appId: '1:63571296037:android:80299872f23f67834764cc',
    messagingSenderId: '63571296037',
    projectId: 'flutterproject-72d57',
    storageBucket: 'flutterproject-72d57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBriT5NZRxKogSRct-0rwmJI57aX6t_qOo',
    appId: '1:63571296037:ios:943b2fff7e3a3c1d4764cc',
    messagingSenderId: '63571296037',
    projectId: 'flutterproject-72d57',
    storageBucket: 'flutterproject-72d57.firebasestorage.app',
    iosBundleId: 'com.example.pagetest2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBriT5NZRxKogSRct-0rwmJI57aX6t_qOo',
    appId: '1:63571296037:ios:943b2fff7e3a3c1d4764cc',
    messagingSenderId: '63571296037',
    projectId: 'flutterproject-72d57',
    storageBucket: 'flutterproject-72d57.firebasestorage.app',
    iosBundleId: 'com.example.pagetest2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADbGCXo2IN-DGmMRAfFHgdzdKYtaC2lMI',
    appId: '1:63571296037:web:a1ec7dab76d57f2d4764cc',
    messagingSenderId: '63571296037',
    projectId: 'flutterproject-72d57',
    authDomain: 'flutterproject-72d57.firebaseapp.com',
    storageBucket: 'flutterproject-72d57.firebasestorage.app',
  );
}
